import goomba from './images/goomba.png';
import upsidedowngoomba from './images/upsidedowngoomba.png';
import paragoomba from './images/paragoomba.png';
import greentroopa from './images/greentroopa.png';
import greenparatroopa from './images/paragreentroopa.png';
import redtroopa from './images/redtroopa.png';
import pararedtroopa from './images/pararedtroopa.png';
import purpletroopa from './images/purpletroopa.png';
import redcheepcheep from './images/redcheepcheep.png';
import upsidedownredcheepcheep from './images/upsidedownredcheepcheep.png';
import greencheepcheep from './images/greencheepcheep.png';
import piranhaplant from './images/piranhaplant.png';
import venusfiretrap from './images/venusfiretrap.png';
import neptuneicetrap from './images/neptuneicetrap.png';
import oilplant from './images/oilplant.png';
import pottedpiranha from './images/pottedpiranha.png';
import ivyplant from './images/ivyplant.png';
import parapiranha from './images/parapiranha.png';
import bulletbill from './images/bulletbill.png';
import missilemark from './images/missilemark.png';
import buzzy from './images/buzzy.png';
import upsidedownbuzzy from './images/upsidedownbuzzy.png';
import spiny from './images/spiny.png';
import upsidedownspiny from './images/upsidedownspiny.png';
import greenspiny from './images/greenspiny.png';
import spinyegg from './images/spinyegg.png';
import lakitu from './images/lakitu.png';
import redlakitu from './images/redlakitu.png';
import shyguy from './images/shyguy.png';
import veggieguy from './images/veggieguy.png';
import snowguy from './images/snowguy.png';
import ninji from './images/ninji.png';
import snifit from './images/snifit.png';
import chainchomp from './images/chainchomp.png';
import giantchomp from './images/giantchomp.png';
import spike from './images/spike.png';
import bobomb from './images/bobomb.png';
import firesnake from './images/firesnake.png';
import podobo from './images/podobo.png';
import pipepodobo from './images/pipepodobo.png';
import ricochetpodobo from './images/ricochetpodobo.png';
import drycheep from './images/drycheeps.png';
import spark from './images/spark.png';
import spintula from './images/spintula.png';
import pyrantula from './images/pyrantula.png';
import thwomp from './images/thwomp.png';
import angrythwomp from './images/angrythwomp.png';
import firebar from './images/firebar.png';
import icebar from './images/icebar.png';
import phanto from './images/phanto.png';
import boo from './images/boo.png';
import polterguy from './images/polterguy.png';
import hammerbros from './images/hammerbros.png';
import firebros from './images/firebros.png';
import icebros from './images/icebros.png';
import piratebros from './images/piratebros.png';
import ninjabros from './images/ninjabros.png';
import flamethrower from './images/flamethrower.png';
import frostthrower from './images/frostthrower.png';
import seamine from './images/seamine.png';
import freezie from './images/freezie.png';
import swoosh from './images/swoosh.png';
import redpixie from './images/redpixie.png';
import bluepixie from './images/bluepixie.png';
import birdo from './images/birdo.png';
import greenbirdo from './images/greenbirdo.png';
import zoomba from './images/zoomba.png';
import kabocha from './images/kabocha.png';
import kabochahopper from './images/kabochahopper.png';
import drybones from './images/drybones.png';


const EnemyList = [
    {
        name: "Goomba",
        description: "Your basic mook of the Bowser Kingdom. Beware, during the day, they will move in Mario's direction when they hit the ground!",
        image: goomba,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Upside Down Goomba",
        description: "These Goombas are enchanted with anti-gravity!",
        image: upsidedowngoomba,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Para Goomba",
        description: "These Goombas have been given wings, allowing them to fly for short bursts. Beware, at night, their flight time increases slightly!",
        image: paragoomba,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Green Koopa Troopa",
        description: "Green shelled Koopas that constantly move forward. Their shell allows them to sustain a couple of fireballs and iceballs before being defeated.",
        image: greentroopa,
        fireballs: 2,
        iceballs: 2,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Green Koopa Para Troopa",
        description: "Green shelled Koopas with wings that bounce around. At night, they have a small amount of hover added to their bounce.",
        image: greenparatroopa,
        fireballs: 2,
        iceballs: 2,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Red Koopa Troopa",
        description: "Red shelled Koopas that march back and forth on a platform. Like their green brethern, their shells makes them take two hits from a fireball or iceball before they are defeated.",
        image: redtroopa,
        fireballs: 2,
        iceballs: 2,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Red Koopa Para Troopa",
        description: "Red shelled Koopas that fly in various patterns. Beware, some Red Koopa Para Troopas will give chase and follow Mario around!",
        image: pararedtroopa,
        fireballs: 2,
        iceballs: 2,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Purple Koopa Troopa",
        description: "Purple shelled Koopas that march back and forth on a platform. Once stomped, they become explosive! Better act quick!",
        image: purpletroopa,
        fireballs: 2,
        iceballs: 2,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Red Cheep Cheep",
        description: "Fiesty fish that like to hope out of the water towards Mario. If it hits land, it'll bounce around wildly!",
        image: redcheepcheep,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Upside Down Red Cheep Cheep",
        description: "This Cheep Cheep will hop out of the water... but upside down?",
        image: upsidedownredcheepcheep,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Green Cheep Cheep",
        description: "Green Cheep Cheeps like to stick to the water, swimming back and forth in a pattern. However, sometimes a Green Cheep Cheep gets brave and will chase Mario around!",
        image: greencheepcheep,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Piranha Plant",
        description: "Piranha Plants move in and out of a pipe, only stopping once Mario is right on top of a pipe. Beware, standing next to a pipe won't stop these plants!",
        image: piranhaplant,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Venus Fire Trap",
        description: "Venus Fire Traps move in and out of pipes, much like Piranha Plants. However, these guys will shoot fireballs at Mario with amazing accuracy! However, at night, they will shoot their fireballs aimlessly.",
        image: venusfiretrap,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Neptune Fire Trap",
        description: "Neptune Ice Traps are much like their Venus Fire Trap cousins, except these will shoot iceballs at Mario! Be ware, they will freeze you on contact!",
        image: neptuneicetrap,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Industrial Oil Plant",
        description: "These bizarre plants were bred to develop oil. However, they now set their sights on Mario! Careful, some surfaces become slick when an oil blob hits it. If Mario is hit by a blob, he will be covered in oil, making everything slick!",
        image: oilplant,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Ivy Piranha Plant",
        description: "Ivy Piranhas can grow to realy great lengths! Once they've gone as far as they can, they will retract for a short period!",
        image: ivyplant,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Potted Piranha",
        description: "Once any version of a Piranha Plant has been taken out of its pipe, it becomes potted! They cannot move in and out anymore, but will continuously attack Mario!",
        image: pottedpiranha,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Para Piranha Plant",
        description: "As bizarre as it looks, some Piranha Plants have wings! They will shoot out at Mario once he's close, but a great height! Becareful as they slowly descend back into their pipe!",
        image: parapiranha,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Bullet Bill",
        description: "Bullet Bills usually come out of turrets and fire straight ahead. They may be fireproof, but can be taken out with an easy stomp!",
        image: bulletbill,
        fireballs: 0,
        iceballs: 0,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Missile Mark",
        description: "Missile Marks look like Bullet Bills, but these guys flash and hone in on Mario! Once they make contact with anything, it will explode. However, Ice Mario can use his iceballs to deactivate the Missle Mark's heat seeking abilities!",
        image: missilemark,
        fireballs: 0,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Buzzy Beetle",
        description: "Buzzy Beetles have a tough shell that protects them from fireballs and iceballs! They can still be stomped and kicked around, though.",
        image: buzzy,
        fireballs: 0,
        iceballs: 2,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Upside Down Buzzy Beetle",
        description: "The upside down variants of Buzzy Beetles crawl along the ceiling. Once you are near them, they will go into their shell and spin towards Mario!",
        image: upsidedownbuzzy,
        fireballs: 0,
        iceballs: 2,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Spiny",
        description: "Spinies have a spiked shell that makes them impervious to being stomped. However, a fireball, iceball, hammer or shuriken will easily take it out!",
        image: spiny,
        fireballs: 2,
        iceballs: 2,
        hammers: 1,
        shurikens: 1,
        stomp: false,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Upside Down Spiny",
        description: "These spines have been enchanted with anti-gravity! However, once Mario is near them, they will spin in their shell and dropped down to attack!",
        image: upsidedownspiny,
        fireballs: 2,
        iceballs: 2,
        hammers: 1,
        shurikens: 1,
        stomp: false,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Green Spiny",
        description: "Unlike their red cousins, Green Spinies will march back and forth on a platform, avoiding the edges.",
        image: greenspiny,
        fireballs: 2,
        iceballs: 2,
        hammers: 1,
        shurikens: 1,
        stomp: false,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Spiny Egg",
        description: "Spiny eggs contain, well, spines! Lakitu will drop these from his cloud in an attempt to attack Mario!",
        image: spinyegg,
        fireballs: 0,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: false,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Lakitu",
        description: "Lakitu rides around in a cloud, tossing various enemies at Mario. He's known for tossing Spiny Eggs, but rumor has it he can throw other enemies, including lighting",
        image: lakitu,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Red Lakitu",
        description: "Red Lakitus are actually Mario's friend! These helpers will ensure Mario always has the power he needs to complete a stage, following him around, ready to provide an item!",
        image: redlakitu,
        fireballs: 0,
        iceballs: 0,
        hammers: 0,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: true,
        wind: false
    },
    {
        name: "Shy Guy",
        description: "Shy Guys have made their way out of Subcon! They've learned a new trick. They are able to pluck blocks out of their place and throw them at Mario!",
        image: shyguy,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Veggie Guy",
        description: "Veggie Guys are green Shy Guys that pluck vegetables from the ground! They will throw these veggies at Mario when they are close enough to him.",
        image: veggieguy,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Snow Guy",
        description: "Snows Guys aren't building snowmen with these snow balls. They'll gather up snow and toss it at Mario in hopes to freeze him in his tracks!",
        image: snowguy,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Ninji",
        description: "Ninji's are back, but deadlier than before! They've learned how to throw shurikens at Mario with deadly accuracy!",
        image: ninji,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Red Snifit",
        description: "Red snifits have switched from shooting pellets to shooting fireballs! Careful when they pause, they will shoot several fireballs at a time!",
        image: snifit,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Chain Chomp",
        description: "Chain Chomps are chomping at the bit to get at Mario! They'll only go as far as their chain will let them, but if they yank too many times, they'll break free!",
        image: chainchomp,
        fireballs: 0,
        iceballs: 0,
        hammers: 2,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Colossal Chomp",
        description: "No chains can hold these bad boys down! They easily munch through anything in their path. Careful, they always fall from the sky!",
        image: giantchomp,
        fireballs: 0,
        iceballs: 0,
        hammers: 0,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: true,
        wind: false
    },
    {
        name: "Spike",
        description: "Spike creates spiked balls that he tosses at Mario. These balls can plow right through bricks.",
        image: spike,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 0,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Bob-omb",
        description: "Bob-ombs tend to come out of pipes. If jumped out, they will explode after a bit. However, if one begins shaking, they'll explode the moment they are tossed into something solid! Careful, a fireball will any Bob-omb to explode immediately!",
        image: bobomb,
        fireballs: 1,
        iceballs: 0,
        hammers: 1,
        shurikens: 0,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Fire Snake",
        description: "Fire Snakes may move a little slow, but if Mario is too far away, they'll charge at him! You can tell they are about to charge as they hesitate for a bit longer before jumping. They also sometimes leave a trail of flames behind them!",
        image: firesnake,
        fireballs: 0,
        iceballs: 2,
        hammers: 0,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: false,
        wind: true
    },
    {
        name: "Podobo",
        description: "These lava bubbles eject out of lava pools, destroying bridges along the way.",
        image: podobo,
        fireballs: 0,
        iceballs: 2,
        hammers: 0,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: false,
        wind: false
    },
    {
        name: "Pipe Podobo",
        description: "Pipe Podobo's eject from one pipe to another. No one is exactly sure how they travel back to their originating pipe, though...",
        image: pipepodobo,
        fireballs: 0,
        iceballs: 2,
        hammers: 0,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: false,
        wind: false
    },
    {
        name: "Ricochet Podobo",
        description: "Podobos that prefer to bounce around the level rather than staying to the lava they came from.",
        image: ricochetpodobo,
        fireballs: 0,
        iceballs: 2,
        hammers: 0,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: false,
        wind: false
    },
    {
        name: "Dry Cheep",
        description: "Dry Cheeps lack any scales, but they will jump around like their red cousins. However, if they land in lava, they will catch fire, making them invulnerable to stomp attacks!",
        image: drycheep,
        fireballs: 0,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: false,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Spark",
        description: "Sparks come from Subcon to hug the ground and walls that Mario treads.",
        image: spark,
        fireballs: 0,
        iceballs: 0,
        hammers: 2,
        shurikens: 4,
        stomp: false,
        tail: false,
        shell: false,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Spintula",
        description: "Spintulas wait above Mario, waiting for him to get close before spinning their webs to drop down on him. Protip: defeat them and use their webs to climb to new areas!",
        image: spintula,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Pyrantula",
        description: "These terrible spiders climb around on fences and spit fireballs at Mario!",
        image: pyrantula,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Thwomp",
        description: "Named for the \"thwomp\" sound they make when hitting the ground, these spiked blocks wait for Mario to get near before slamming into the ground. They can break bricks and cracked floors upon impact.",
        image: thwomp,
        fireballs: 0,
        iceballs: 0,
        hammers: 3,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: false,
        wind: false
    },
    {
        name: "Impatient Thwomp",
        description: "These guys don't wait for Mario to get close, they just continuously slam into the ground and ceiling! Better watch your timing.",
        image: angrythwomp,
        fireballs: 0,
        iceballs: 0,
        hammers: 3,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: false,
        wind: false
    },
    {
        name: "Fire Bar",
        description: "A bar of fireballs that spin clockwise or counter-clockwise.",
        image: firebar,
        fireballs: 0,
        iceballs: 0,
        hammers: 0,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: true,
        wind: false
    },
    {
        name: "Ice Bar",
        description: "Like fire bars, except these icy versions will freeze Mario and toss him away, hopefully not into a pit!",
        image: icebar,
        fireballs: 0,
        iceballs: 0,
        hammers: 0,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: true,
        wind: false
    },
    {
        name: "Phanto",
        description: "A mysterious mask that guards a key. Grabbing the key will waken the Phanto and cause him to chase Mario. Letting go of the key provides temporary relief, but grab it again and Phanto will return!",
        image: phanto,
        fireballs: 0,
        iceballs: 0,
        hammers: 1,
        shurikens: 1,
        stomp: false,
        tail: false,
        shell: true,
        dash: false,
        nodeath: false,
        wind: false
    },
    {
        name: "Boo",
        description: "A timid ghost that only chases Mario if he's looking away.",
        image: boo,
        fireballs: 0,
        iceballs: 0,
        hammers: 0,
        shurikens: 2,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: false,
        wind: false
    },
    {
        name: "Polter Guy",
        description: "The undead cousins of the Shy Guy family. They simply hover back and forth.",
        image: polterguy,
        fireballs: 0,
        iceballs: 0,
        hammers: 0,
        shurikens: 2,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: false,
        wind: false
    },
    {
        name: "Hammer Bros",
        description: "Back again, these brothers continuously throw hammers at Mario. However, their hammers are able to break bricks and activate blocks, just like Mario's hammers!",
        image: hammerbros,
        fireballs: 3,
        iceballs: 3,
        hammers: 2,
        shurikens: 3,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Fire Bros",
        description: "Fire brothers move about, shooting fireballs from their mouth.",
        image: firebros,
        fireballs: 0,
        iceballs: 3,
        hammers: 2,
        shurikens: 3,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Ice Bros",
        description: "A more frigid brother who shoots iceballs at Mario.",
        image: icebros,
        fireballs: 3,
        iceballs: 0,
        hammers: 2,
        shurikens: 3,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Pirate Bros",
        description: "Scurge othe sea, these bad brothers spit cannonballs at Mario! How weird!",
        image: piratebros,
        fireballs: 3,
        iceballs: 3,
        hammers: 2,
        shurikens: 3,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Ninja Bros",
        description: "Pirates vs ninjas? The brothers have ninja clans in the family! These shadow figures will disappear in a puff of smoke and reappear on a new platform. They toss shurikens at Mario with incredible accuracy.",
        image: ninjabros,
        fireballs: 3,
        iceballs: 3,
        hammers: 2,
        shurikens: 0,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Flame Thrower",
        description: "This industrial tool periodically shoots a stream of fire. This can hurt enemies as well!",
        image: flamethrower,
        fireballs: 0,
        iceballs: 0,
        hammers: 0,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: true,
        wind: false
    },
    {
        name: "Frost Thrower",
        description: "Frost throwers produce a stream of frost that will freeze enemies and Mario!",
        image: frostthrower,
        fireballs: 0,
        iceballs: 0,
        hammers: 0,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: true,
        wind: false
    },
    {
        name: "Sea Mine",
        description: "These mines float deep under the sea. If Mario gets close, they will release from their chain and float upwards, exploding on contact with anything.",
        image: seamine,
        fireballs: 1,
        iceballs: 0,
        hammers: 1,
        shurikens: 0,
        stomp: false,
        tail: false,
        shell: false,
        dash: false,
        nodeath: false,
        wind: false
    },
    {
        name: "Freezie",
        description: "An old foe from Mario's earlier days, Freezie like to hide in pipes and will freeze him on contact. Freezies also freeze the surface of water that they touch.",
        image: freezie,
        fireballs: 1,
        iceballs: 0,
        hammers: 1,
        shurikens: 1,
        stomp: false,
        tail: false,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Swoosh",
        description: "Swooshes might be tiny clouds, but they will swell with air and blow hard to push Mario off into a ledge.",
        image: swoosh,
        fireballs: 0,
        iceballs: 0,
        hammers: 1,
        shurikens: 1,
        stomp: false,
        tail: false,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Red Pixie",
        description: "Red Pixies have a fireball swirling around them, melting ice blocks and harming Mario.",
        image: redpixie,
        fireballs: 0,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Blue Pixie",
        description: "Blue Pixies have an iceball swirling around them, freezing water and Mario on contact.",
        image: bluepixie,
        fireballs: 1,
        iceballs: 0,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: true,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Birdo",
        description: "Birdos are back! They are definitely tougher than your normal mook! They can be stood on and they shoot eggs at Mario. Careful, if Mario is hit by an egg, he's yolked and can't run or attack!",
        image: birdo,
        fireballs: 5,
        iceballs: 5,
        hammers: 3,
        shurikens: 5,
        stomp: false,
        tail: false,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Green Birdo",
        description: "The green sister of Birdo has ditched the eggs and prefers to shoot big fireballs at Mario!",
        image: greenbirdo,
        fireballs: 5,
        iceballs: 5,
        hammers: 3,
        shurikens: 5,
        stomp: false,
        tail: false,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Zoomba",
        description: "Zombie Goombas?! Zoombas are tougher than their living cousins. They move faster, will jump over small walls and will infect Mario on contact! They sometimes hide in the ground, so watch out!",
        image: zoomba,
        fireballs: 3,
        iceballs: 3,
        hammers: 2,
        shurikens: 2,
        stomp: false,
        tail: false,
        shell: true,
        dash: true,
        nodeath: false,
        wind: true
    },
    {
        name: "Kabocha",
        description: "These pumpkin headed plants live inside of pipes. Sometimes they will spit fireballs at Mario. When you attack them, their stems are destroyed, leaving the head to attack!",
        image: kabocha,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: false,
        tail: false,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Kabocha Head",
        description: "Kabochas will hop around mad if you destory their stems. They're fast and stop at nothing to get at Mario!",
        image: kabochahopper,
        fireballs: 1,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: false,
        tail: false,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    },
    {
        name: "Dry Bones",
        description: "These undead Koopas now have a new behavior - stomping on them causes their head to detach and chase Mario around for a moment before reattaching to the body.",
        image: drybones,
        fireballs: 0,
        iceballs: 1,
        hammers: 1,
        shurikens: 1,
        stomp: true,
        tail: false,
        shell: true,
        dash: true,
        nodeath: false,
        wind: false
    }
];

export default EnemyList;